version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/" 
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "org.projectlombok:lombok"
        versions:
          - "*"
      - dependency-name: "com.google.guava:guava"
        versions:
          - "*"
