spring:
  application:
    name: IoT-service
dubbo:
  application:
    name: IoT-service
  registry:
    address: nacos://101.42.157.163:8848
    username: nacos
    password: nacos

influx:
  token: p2w7KvUNaax9hNcnVsTJDGMCt1Xi80yRaZZIVDro68YbTBjjLzpn5Lf3hn3zDbfcwz6A1H4eBoFm95oSLzaRnw==

# Actuator 配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
server:
  port: 18016

