# Prometheus 配置文件
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'iot-device'
    metrics_path: '/actuator/prometheus'
    static_configs:
      #      这里要替换
      - targets: [ '192.168.1.20:18097' ]
    scrape_interval: 10s
    scrape_timeout: 5s

  - job_name: 'iot-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '192.168.1.20:18016' ]
    scrape_interval: 10s
    scrape_timeout: 5s
