spring:
  application:
    name: repair-service
  ai:
    openai:
      base-url: http://127.0.0.1:11434
      api-key: ollama
      chat:
        options:
          model: qwen2.5:7b
logging:
  level:
    org.springframework.ai: debug
    com.ncwu.repairservice: debug
server:
  port: 20000
dubbo:
  application:
    name: repair-service
  registry:
    address: nacos://101.42.157.163:8848
    username: nacos
    password: nacos